# Generated by Django 5.0.7 on 2024-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0003_product_brand_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
