# Generated by Django 5.0.7 on 2024-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0007_alter_product_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to='products'),
        ),
    ]
