# Generated by Django 5.0.7 on 2024-07-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0010_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_care', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_discount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
