# Generated by Django 5.0.7 on 2024-07-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0011_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
