# Generated by Django 5.0.7 on 2024-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0014_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
