# Generated by Django 5.0.7 on 2024-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0015_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
