# Generated by Django 5.0.7 on 2024-07-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapo', '0021_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
